version: '3.9'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=go-rest      
    ports:
      - "5432:5432"
    volumes:
      - ../migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql